apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: veg-sc
  namespace: saurav-ns 
provisioner: ebs.csi.aws.com
parameters:
  type: gp3  # general purpose SSD (gp3, gp2)
reclaimPolicy: Retain 
volumeBindingMode: WaitForFirstConsumer
